import { Image } from 'react-grid-gallery';
const imageStore = [
    '/images/blog/blog-3.jpg',
    '/images/blog/blog-4.jpg',
    '/images/blog/blog-5.jpg',
    '/images/blog/blog-6.jpg',
    '/images/blog/blog-7.jpg',
    '/images/blog/blog-8.jpg',
    '/images/blog/blog-2.jpg',
    '/images/blog/blog-1.jpg',
    '/images/cat/baby-cat.jpg',
    '/images/dog/gallery1.jpg',
    '/images/dog/gallery2.jpg',
    '/images/dog/gallery3.jpg',
    '/images/dog/gallery4.jpg',
    '/images/dog/gallery5.jpg',
    '/images/dog/gallery6.jpg',
    '/images/dog/golden.jpg',
    '/images/team/team-2.jpg',
    '/images/team/team-4.jpg',
];
const imageStore2 = [
    '/images/dog/gallery6.jpg',
    '/images/cat/baby-cat.jpg',
    '/images/cat/meo-1-333.jpg',
    '/images/cat/meo-ba-tu.jpg',
    '/images/cat/meo-trang.jpg',
    '/images/dog/gallery3.jpg',
    '/images/dog/gallery4.jpg',
    '/images/dog/gallery5.jpg',
    '/images/cat/meo-vang.jpg',
    '/images/dog/Alaska.jpg',
    '/images/dog/chihuahua.jpg',
    '/images/dog/chó lạp xưởng.png',
    '/images/dog/dog2.jpg',
    '/images/dog/samoyed.jpg',
    '/images/dog/shiba.jpg',

    '/images/team/team-alt-1.jpg',
    '/images/team/team-alt-2.jpg',

    '/images/team/team-5.jpg',
];
const imageStore3 = [
    '/images/dog/gallery-2.jpg',
    '/images/dog/gallery-3.jpg',
    '/images/dog/gallery-9.jpg',
    '/images/dog/gallery-5.jpg',
    '/images/dog/gallery-6.jpg',
    '/images/dog/gallery-7.jpg',
    '/images/dog/gallery-8.jpg',
    '/images/services/service_details-2.jpg',
    '/images/services/service-details-1.jpg',
    '/images/services/service1.jpg',
    '/images/services/service2.jpg',
    '/images/services/service3.jpg',
    '/images/services/service4.jpg',
    '/images/team/team-alt-3.jpg',
    '/images/team/team-alt-4.jpg',
];

export const images = [
    {
        src: '/images/blog/blog-3.jpg',
        original: '/images/blog/blog-3.jpg',
        width: 340,
        height: 294,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Flora', title: 'Flora' },
        ],
        caption: 'After Rain (Jeshu John - designerspics.com)',
    },
    {
        src: '/images/blog/blog-4.jpg',
        original: '/images/blog/blog-4.jpg',
        width: 320,
        height: 212,
        caption: 'Boats (Jeshu John - designerspics.com)',
    },
    {
        src: '/images/blog/blog-5.jpg',
        original: '/images/blog/blog-5.jpg',
        width: 320,
        height: 212,
        caption: 'Color Pencils (Jeshu John - designerspics.com)',
    },
    {
        src: '/images/blog/blog-6.jpg',
        original: '/images/blog/blog-6.jpg',
        width: 320,
        height: 213,
        caption: 'Red Apples with other Red Fruit (foodiesfeed.com)',
    },
    {
        src: '/images/blog/blog-7.jpg',
        original: '/images/blog/blog-7.jpg',
        width: 320,
        height: 183,
        caption: '37H (gratispgraphy.com)',
    },
    {
        src: '/images/blog/blog-8.jpg',
        original: '/images/blog/blog-8.jpg',
        width: 640,
        height: 420,
        tags: [{ value: 'Nature', title: 'Nature' }],
        caption: '8H (gratisography.com)',
    },
    {
        src: '/images/blog/blog-1.jpg',
        original: '/images/blog/blog-1.jpg',
        width: 320,
        height: 190,
        caption: '286H (gratisography.com)',
    },
    {
        src: '/images/blog/blog-2.jpg',
        original: '/images/blog/blog-2.jpg',
        width: 320,
        height: 248,
        tags: [{ value: 'People', title: 'People' }],
        caption: '315H (gratisography.com)',
    },
    {
        src: '/images/cat/baby-cat.jpg',
        original: '/images/cat/baby-cat.jpg',
        width: 320,
        height: 213,
        caption: '201H (gratisography.com)',
    },
    {
        src: '/images/dog/gallery1.jpg',
        original: '/images/dog/gallery1.jpg',
        alt: 'Big Ben - London',
        width: 248,
        height: 320,
        caption: 'Big Ben (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/gallery2.jpg',
        original: '/images/dog/gallery2.jpg',
        alt: 'Red Zone - Paris',
        width: 320,
        height: 313,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Red Zone - Paris (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/gallery3.jpg',
        original: '/images/dog/gallery3.jpg',
        alt: 'Wood Glass',
        width: 513,
        height: 320,
        caption: 'Wood Glass (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/gallery4.jpg',
        original: '/images/dog/gallery4.jpg',
        width: 320,
        height: 213,
        caption: 'Flower Interior Macro (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/gallery5.jpg',
        original: '/images/dog/gallery5.jpg',
        width: 320,
        height: 194,
        caption: 'Old Barn (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/gallery6.jpg',
        original: '/images/dog/gallery6.jpg',
        alt: 'Cosmos Flower',
        width: 520,
        height: 413,
        caption: 'Cosmos Flower Macro (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/golden.jpg',
        original: '/images/dog/golden.jpg',
        width: 671,
        height: 420,
        caption: 'Orange Macro (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/team/team-2.jpg',
        original: '/images/team/team-2.jpg',
        width: 320,
        height: 213,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'People', title: 'People' },
        ],
        caption: 'Surfer Sunset (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/cat/meo-1-333.jpg',
        original: '/images/cat/meo-1-333.jpg',
        width: 350,
        height: 213,
        tags: [
            { value: 'People', title: 'People' },
            { value: 'Sport', title: 'Sport' },
        ],
        caption: 'Man on BMX (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/team/team-4.jpg',
        original: '/images/team/team-4.jpg',
        width: 320,
        height: 213,
        caption: 'Ropeman - Thailand (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/cat/meo-vang.jpg',
        original: '/images/cat/meo-vang.jpg',
        width: 320,
        height: 213,
        caption: 'Time to Think (Tom Eversley - isorepublic.com)',
    },
    {
        src: '/images/dog/Alaska.jpg',
        original: '/images/dog/Alaska.jpg',
        width: 320,
        height: 179,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Fauna', title: 'Fauna' },
        ],
        caption: 'Untitled (Jan Vasek - jeshoots.com)',
    },
    {
        src: '/images/dog/chihuahua.jpg',
        original: '/images/dog/chihuahua.jpg',
        width: 320,
        height: 215,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/dog/chó lạp xưởng.png',
        original: '/images/dog/chó lạp xưởng.png',
        width: 457,
        height: 320,
        caption: 'A photo by 贝莉儿 NG. (unsplash.com)',
    },
    {
        src: '/images/dog/dog2.jpg',
        original: '/images/dog/dog2.jpg',
        width: 276,
        height: 320,
        caption: 'A photo by Matthew Wiebe. (unsplash.com)',
    },
    {
        src: '/images/dog/samoyed.jpg',
        original: '/images/dog/samoyed.jpg',
        width: 320,
        height: 179,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Fauna', title: 'Fauna' },
        ],
        caption: 'Untitled (Jan Vasek - jeshoots.com)',
    },
    {
        src: '/images/dog/shiba.jpg',
        original: '/images/dog/shiba.jpg',
        width: 320,
        height: 215,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/team/team-alt-1.jpg',
        original: '/images/team/team-alt-1.jpg',
        width: 320,
        height: 279,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Fauna', title: 'Fauna' },
        ],
        caption: 'Untitled (Jan Vasek - jeshoots.com)',
    },
    {
        src: '/images/team/team-alt-2.jpg',
        original: '/images/team/team-alt-2.jpg',
        width: 320,
        height: 265,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/team/team-5.jpg',
        original: '/images/team/team-5.jpg',
        width: 457,
        height: 320,
        caption: 'A photo by 贝莉儿 NG. (unsplash.com)',
    },
    {
        src: '/images/dog/gallery-2.jpg',
        original: '/images/dog/gallery-2.jpg',
        width: 426,
        height: 320,
        caption: 'A photo by Matthew Wiebe. (unsplash.com)',
    },
    {
        src: '/images/dog/gallery-3.jpg',
        original: '/images/dog/gallery-3.jpg',
        width: 320,
        height: 379,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Fauna', title: 'Fauna' },
        ],
        caption: 'Untitled (Jan Vasek - jeshoots.com)',
    },
    {
        src: '/images/dog/gallery-5.jpg',
        original: '/images/dog/gallery-5.jpg',
        width: 320,
        height: 215,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/dog/gallery-7.jpg',
        original: '/images/dog/gallery-7.jpg',
        width: 320,
        height: 279,
        tags: [
            { value: 'Nature', title: 'Nature' },
            { value: 'Fauna', title: 'Fauna' },
        ],
        caption: 'Untitled (Jan Vasek - jeshoots.com)',
    },
    {
        src: '/images/dog/gallery-8.jpg',
        original: '/images/dog/gallery-8.jpg',
        width: 320,
        height: 265,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/services/service_details-2.jpg',
        original: '/images/services/service_details-2.jpg',
        width: 257,
        height: 320,
        caption: 'A photo by 贝莉儿 NG. (unsplash.com)',
    },
    {
        src: '/images/services/service-details-1.jpg',
        original: '/images/services/service-details-1.jpg',
        width: 626,
        height: 320,
        caption: 'A photo by Matthew Wiebe. (unsplash.com)',
    },
    {
        src: '/images/services/service1.jpg',
        original: '/images/services/service1.jpg',
        width: 320,
        height: 265,
        tags: [{ value: 'People', title: 'People' }],
        caption: 'Untitled (moveast.me)',
    },
    {
        src: '/images/services/service2.jpg',
        original: '/images/services/service2.jpg',
        width: 957,
        height: 570,
        caption: 'A photo by 贝莉儿 NG. (unsplash.com)',
    },
    {
        src: '/images/services/service3.jpg',
        original: '/images/services/service3.jpg',
        width: 626,
        height: 420,
        caption: 'A photo by Matthew Wiebe. (unsplash.com)',
    },
    {
        src: '/images/team/team-alt-4.jpg',
        original: '/images/team/team-alt-4.jpg',
        width: 1057,
        height: 720,
        caption: 'A photo by 贝莉儿 NG. (unsplash.com)',
    },
    {
        src: '/images/team/team-alt-3.jpg',
        original: '/images/team/team-alt-3.jpg',
        width: 626,
        height: 420,
        caption: 'A photo by Matthew Wiebe. (unsplash.com)',
    },
];
