const routes = {
    home: '/',
    services: '/services',
    servicesDetail: '/services/:slug/detail',
    news: '/news/dog/category',
    newsDetail: '/news/:cate/:slug/detail',
    newsCategory: '/news/:slug/category',
    contact: '/contact',
    login: '/login',
    register: '/register',
    profile: '/profile',
    store: '/store',
    storeDetail: '/storeDetail/:slug',
    team: '/team',
    teamCategory: '/team/:category',
    teamDetail: '/team/:slug/detail',
    gallery: '/gallery',
    cart: '/store/cart',
    payment: '/store/cart/payment',
    page404: '*',
    purchaseOrder: '/purchase',

    admin: '/admin/:slug',
    adminHomePage: '/admin/homepage',
    adminQltkPersonnel: '/admin/qltkpersonnel',
    adminQltkUsers: '/admin/qltkusers',
    adminQlsp: '/admin/qlsp',
    adminQlspEdit: '/admin/qlsp-edit',
    adminQlspAdd: '/admin/qlsp-add',
    adminQllsq: '/admin/qllsp',
    adminQldv: '/admin/qldv',
    adminQldvEdit: '/admin/qldv-edit',
    adminQldvAdd: '/admin/qldv-add',
    adminduyetdichvu: '/admin/duyetdichvu',
    thanhtoandichvu: '/admin/duyetthanhtoandichvu',
    duyetdonhang: '/admin/duyetdonhang',
};
export default routes;
